### ISSUE TITLE
readme example doesn't really work.

### ISSUE THREAD

**Issue by duralog** [dominictarr/npmd-install#7]
```
$ npmd-resolve browserify | npmd-install

/usr/local/lib/node_modules/npmd-install/node_modules/npmd-cache/index.js:26
  if(!db) throw new Error('must have db and config')
                ^
Error: must have db and config
    at module.exports (/usr/local/lib/node_modules/npmd-install/node_modules/npmd-cache/index.js:26:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npmd-install/index.js:181:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)

```

appears this happened in a refactor. anyway, npmd-cache is called with (null, config) in npmd-install, so obviously in npmd-cache it will complain -- one of the first lines is `if(!db) throw new Error('must have db and config')`

so, after looking at it a bit, I don't know how you'd like to fix it - but it doesn't make much sense to add levelup/leveldown deps into npmd-install, so I recommend, in npmd-cache, if (!db && config) to initialize the db directly out of the config - however, you will then have redundant code in npmd/index.js:31 (`createDb`) - so instead maybe that function can be moved right into npmd-cache.

ok man it's a solid design from what I see so far. nice!

**Comment by dominictarr** [comment]
hmm, yeah I'm not really sure either. One thing I would like to get rid of is the leveldb instance.
leveldb is great, but having a binary compile step is slow and a major butthurt on windows.
There isn't that much data needed so it could be replaced with a js only database like https://github.com/louischatriot/nedb (although I'd want to write a leveldown wrapper for that!)

**Comment by dominictarr** [comment]
I've also been considering just using http://github.com/dominictarr/json-logdb which is actually just an append-only file.

**Comment by dominictarr** [comment]
Also, see [rc](https://github.com/dominictarr/rc) for how configuration is loaded.
If you put `"greedy": true` in the config file it will be always on.
I'm reluctant to turn it on by default since it's quite a departure from how npm works.

**Comment by dominictarr** [comment]
I have not been able to confirm this bug. This seems to work for me...
are you using the latest npmd?

**Comment by dominictarr** [comment]
oh oops those comments where meant for your other issue

**Comment by dominictarr** [comment]
https://github.com/dominictarr/npmd/issues/73

**Comment by duralog** [comment]
woah bro - 20 rapid fire comments :) hehe

lemme see. I'm going to try again now.. if there's a problem, I'll reply.

as for the database, I see two super quick solutions:
1. just fs.readFile -> JSON.parse -- do updates JSON.stringify -> fs.writeFile
2. just use your json-logdb and store every procedure, eg. {path: "my.deep.json.path", op: ['push', 'pop', 'slice', 'set', 'delete']} on its own line, then when loading, run the whole log.
3. combine 1 and 2, and consider the json as the "snapshot"

I actually prefer the second (or third) idea, as that means undo/revert could be added easily. additionally the advantage of combinng the two, is when the log gets really big, just save a snapshot and use that as the starting point.

even if leveldb became optional by default, I'm sure that the performance wouldn't even be a big deal. let's say the db file grows to be 200k ... and that's a lot of npm metadata... even still, it wouldn't be a big load... readfile (if you don't stream it) and then a JSON.parse ... if performance becomes a problem, I could see "sharding" the database over files like git does in the objects dir

ok, very well then :) good night

**Comment by dominictarr** [comment]
okay so we will switch to medeadown - https://github.com/dominictarr/npmd/pull/76
and that will mean no compiling.

I'm not sure what you mean about the replayable operations. What problem will that solve?

**Comment by duralog** [comment]
I meant, if you have a snapshot of the db (json file) and then a replay log (json-logdb) you could just replay the log on top of your snapshot anytime you start npmd... however after looking at medea/medeadown, I can clearly see that it is far superior than a replay log/json.stringify approach.

yeah, I do think that is the best way to go :)

**Comment by duralog** [comment]
hey, last thing: I just installed the latest version, and it still doesn't work. npmd-install will try and `require('level')` (line 189) - which is not a part of its dependencies. if I `npmd install level -g --greedy` it will indeed function properly. - however this doesn't affect me, because I already have level as one of my dependencies...

nice! good luck with the medeadown conversion. quick thinking, it shouldn't be too hard. I think if you just check if path.exists(level_db_path) then just npmd install npmd-leveldb-cleanup and then spawn that module in a detached process. it should createReadStream on the old db, pipe it into the new one, then delete itself. right?

**Comment by dominictarr** [comment]
I think the simpler solution would be just to have a separate migration tool,
and post an error message instructing the user to run it - less magic / weird edge cases there

**Comment by duralog** [comment]
you sure? imo, the separate migration tool should only need manual attention if the automatic one fails... I really dislike having to do stuff manually, and additionally - if it didn't operate transparently, instead it would break every script with npmd commands in it, that is, until the migration tool has been run.

**Comment by dominictarr** [comment]
yeah, but it's just too hard to get something like that to magically work, hmm, best would be to run the script immediately after installing the latest version?

**Comment by duralog** [comment]
yep, I meant, in package.json > scripts.install: "node ./scripts/migrate-leveldown.js"
migrate-leveldown.js does this:
1. run npmd-config and check for existing level db existence
2. if found:
- ensure level is installed
- open medeadown and create writeStream
- open leveldown db and create a readStream
- pipe it
- delete level db file
- delete level from node_modules

seems easy to me. maybe 50 lines or so. want me to write it?

**Comment by duralog** [comment]
oh and to clarify: I realized that the install script is the best way, so I no longer mean to say a separate module or a detached spawn anymore. (old instances of npmd will continue as is)... however, perhaps you may want to save a manifest somewhere like multilevel does and after x time/ops do a cleanup in a detached process after the npmd command has completed.

**Comment by dominictarr** [comment]
Actually, after posting that I realized that the failure case is quite soft.
If you switch the database types, it will still work, only the cache of url->hash mappings will be empty.
so, it will still work, but some offline installs wont work until you have installed it again.
so all the migration script would do is reupdate your cache.

**Comment by duralog** [comment]
oh wait, you're gonna make the db configurable? that'd be cool cause then any *down db could be used.

an idea: let the backend be configurable, where it has the normal leveldown compatible interface, plus an additional method to destroy() (which removes/empties the db or does nothing).

these use cases are discovered:
-  someone switches the backend
  - newdown.open() - assumed to have already been done by npmd, actually
  - rs = newdown.createWriteStream()); ws = olddown.createReadStream(); rs.pipe(ws)
  - rs.on('end', function() { olddown.destroy() })
- someone wants to populate their db
  - open json stream of a dump (could by like the couchdb sync)
  - pipe it into the db
-  normal operation

I can see this being _very_ useful if someone wants to use a networked db for this. they'd only need to write thier redisdown / memcachedown / mysqldown / etc. and npmd won't know the difference :)

cheers

**Comment by dominictarr** [comment]
I'm not planning on making the db configurable, just planning on switching to a database that does not require compliation, which will make installation a bit simpler.

Although, I do have a plan to add a resolution server, which will bring some of the features of npmd@0 back into play, where the npm registry is replicated locally and so it can resolve very quickly (it would keep deps in a leveldb, and resolve without doing network io),
and also keep a cache of what everyone (in your office, say) installs, so that you shouldn't be affected by npm downtime, etc.
